# Generated by Django 5.1.4 on 2025-06-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description',
            new_name='content',
        ),
    ]
