# Generated by Django 5.1.4 on 2025-06-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_description_posts_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.CharField(default='username', max_length=255),
        ),
    ]
